
# Free the original Ctrl-b prefix keybinding
unbind C-b
# Set prefix to Ctrl-space
set -g prefix C-Space
# Allow a process to accept Ctrl-space in tmux window, by pressing Ctrl-space twice.
bind-key C-Space send-prefix

# setting the delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# moving between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# splitting panes with \ and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse
set -g mouse on

# Set the default terminal mode to 256color mode
set -g default-terminal "xterm-256color"

# Set  -g default-terminal "xterm-256color"
set -ga terminal-overrides ',xterm-256color:Tc'

setw -g mode-keys vi

# enable system clipboard
set -s set-clipboard on

# Command / message line
#set -g message-style fg='#f6f4f2',bold,bg='#425664'

# enable activity alerts
setw -g monitor-activity on
set -g visual-activity on
#setw -g window-status-activity-style bg=color1

set-option -g status-position top

 # List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
run ~/.tmux/plugins/catppuccin-tmux/catppuccin.tmux # installed manually no tpm

# Theme config
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"

set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "application session user host"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_application_icon ""
set -g @catppuccin_application_color "#50B498"

# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
