
# Free the original Ctrl-b prefix keybinding
unbind C-b
# Set prefix to Ctrl-space
set -g prefix C-Space
# Allow a process to accept Ctrl-space in tmux window, by pressing Ctrl-space twice.
bind-key C-Space send-prefix

# setting the delay between prefix and command
set -s escape-time 1

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# moving between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# splitting panes with \ and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse
set -g mouse on

# Set the default terminal mode to 256color mode
set -g default-terminal "xterm-256color"

# Set  -g default-terminal "xterm-256color"
set -ga terminal-overrides ',xterm-256color:Tc'

setw -g mode-keys vi

# enable system clipboard
set -s set-clipboard on

# Command / message line
#set -g message-style fg='#f6f4f2',bold,bg='#425664'

#setw -g window-status-activity-style bg=color1

 # List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# To update plugin for future revisions or bug fixes, do the "Prefix + U" keycomboet -g @plugin 'tmux-plugins/tmux-yank'
# DESIGN TWEAKS
# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right ''
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'
set-option -g status-position top

# messages
set -g message-style 'fg=yellow bg=red bold'

# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
