# General Configuration
[colors]
background=282a36fa
selection=3d4474fa
border=fffffffa

# output=<not set>
dpi-aware=auto
prompt=""
fields=name,generic,comment,categories,filename,keywords
password-character=*
filter-desktop=no
match-mode=fzf
show-actions=yes
terminal=foot -e
 
# Border Settings
[border]
width=0
radius=8

# dmenu Settings
[dmenu]
# mode=text  # text|index
exit-immediately-if-empty=no
