# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = FiraCodeNerdFont-Regular
# $battery = ./battery.sh

general {
    hide_cursor = false
}

 uncomment to enable fingerprint authentication
 auth {
     fingerprint {
         enabled = true
         ready_message = Scan fingerprint to unlock
         present_message = Scanning...
         retry_delay = 250 # in milliseconds
     }
 }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/alfa.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 1

    inner_color = rgba(18, 18, 18, 0.8)
    outer_color = rgba(72, 61, 139, 0.85) rgba(60, 179, 113, 0.85) 135deg
    check_color = rgba(50, 205, 50, 0.85) rgba(173, 255, 47, 0.85) 100deg
    fail_color = rgba(220, 20, 60, 0.85) rgba(178, 34, 34, 0.85) 60deg
    font_color = rgb(225, 225, 225)

    fade_on_empty = true
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font
    color = rgba(56, 111, 164, 1)

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B" # update every 60 seconds
    font_size = 25
    font_family = $font
    color = rgba(155, 193, 188, 1)

    position = -30, -150
    halign = right
    valign = top
}

# Battery
label {
    monitor =
    # Cerulean #4281A4
    # Tropical Teal #48A9A6

    text = cmd[update:10000] echo "<span foreground='##48A9A6'>  $(< /sys/class/power_supply/BAT0/capacity)%</span>"
    # text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"
    font_size = 20
    font_family = $font

    position = -30, -220
    halign = right
    valign = top
}
