[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

# [[language]]
# name = "python"
# # use pylsp-mypy for mypy
# language-servers = ["pylsp", "ruff"]
# formatter = { command = "ruff", args = ["format", "-n", "-"] }
# auto-format = true

# [language-server.ruff]
# command = "ruff"
# args = ["server", "--preview"]
# config = { settings = { organizeImports = true, lint.run = "onSave" } }

[[language]]
name = "yaml"
file-types = ["yml", "yaml", { glob = "phpstan.neon" }]

[[language]]
name = "git-config"
file-types = [
  { glob = "git/config" },
  { glob = ".gitmodules" },
  { glob = ".gitconfig" },
  { glob = ".git/config" },
  { glob = ".config/git/config" },
]

[language-server.clangd]
command = "clangd"
args = ["--clang-tidy", "-j=5", "--malloc-trim"]

[[language]]
name = "c"
language-servers = [
  "clangd",
  { name = "efm", only-features = [
    "diagnostics",
  ] }, # gcc, clang-analyzer and cppcheck lints
]
file-types = ["c", "h"]
auto-format = true

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "pkgbuild"
language-servers = [
  "pkgbuild-language-server",
  { name = "bash-language-server", except-features = [
    # "diagnostics",
  ] },
]
auto-format = true

# [language-server.rust-analyzer.config.check]
# command = "clippy"

# [language-server.rust-analyzer.config.cargo]
# features = "all"
